### ISSUE TITLE
PhotoView version 1.7 not working for Screensaver

### ISSUE THREAD

**Issue by timrit** [chtaylo2/Roku-GooglePhotos#70] opened 2017-11-16 17:38 UTC
Sorry if this is a repeat, but not seeing original post.  I’m using a Roku TV with build 7.7.  Screensaver will not work. It shows the PhotoView splash screen that it is “Loading...” but after 1-2 minutes just show the default Roku City Walk Screensaver.
Probably related: if I’m in the actual app and choose the Shuffle Photos slideshow , I will get the same City Walk screensaver HOWEVER, if I then press a key, I will see an API Error box.   I press the the enter key to release the API Error box, THEN it will start a slideshow that does seem truly random (thx!).  FYI I have over 90,000 pics in my google photos db. Let me know if you need more details...

**Comment by chtaylo2** [comment] 2017-11-20 05:53
The issue is most likely due to this: https://github.com/chtaylo2/Roku-GooglePhotos/issues/38

How many albums do you have? Please do the following and I'll try to review:

1.) Login to http://photos.google.com
2.) This in the same browner goto: https://picasaweb.google.com/data/feed/api/user/default?fields=entry%28title%2Cgphoto%3Anumphotos%2Cgphoto%3Auser%2Cgphoto%3Aid%2Cmedia%3Agroup%28media%3Adescription%2Cmedia%3Athumbnail%29%29&kind=album&thumbsize=220&v=2.0

3.) Past the contents in a text file and email to me: rokuphotoview@gmail.com

Thanks
Chris

**Comment by timrit** [comment] 2017-11-28 17:10
Chad, trying to go to the picasaweb.google.com link above and I get back "Internal Error.  Try again later".  Using chrome in a Win10 environment.

**Comment by timrit** [comment] 2017-11-30 16:40
...and I have about 90 albums.

**Comment by chtaylo2** [comment] 2018-01-02 15:17
If you're getting an Internal Error using the above link, something in your albums is not being friendly to the Google API. Can you try again, different browser maybe? The application is being rewritten with a targeted MVP for end of January. I'll get you the beta Roku channel ID to test with, once I'm at a good point. 

90 albums shouldn't be cause an issue. There's folks out there with thousands of albums.

Thanks

**Comment by chtaylo2** [comment] 2018-01-30 20:39
Please try the beta version of v.2.0: https://my.roku.com/account/add?channel=RZ5TQ6

Let me know if that fixes your issue.

**Comment by timrit** [comment] 2018-01-30 22:22
Wow!  It's working great!  All albums are now showing up after about a 10 sec delay.  Tried different combinations of SD vs HD, different display methods, slideshow order.  Even videos are working!  

Updated the Roku slideshow settings and looks like it starts up after about a 20 second pause (multi-scrolling HD) and is working perfectly!

Nice work Chris.  I'll keep hammering away to see if I can get something to break, but seriously 10 out 10 so far...let me know if you need me to try something specific.  FYI says I have 110k pics.

**Comment by timrit** [comment] 2018-01-31 16:30
After day, all seems to be working well.  Some suggestions/comments for v2:

1. I love the  multi-scrolling photo option.  You may want to Increase the pic size of the multi scrolling pics by at least 50%, maybe even 2x. I have a 55 inch Roku TV.  I don't mind if they overlap, it's part of the character. Also you could even slow the scroll by say 20-50% as well...

2.  Another thought for the order of the multi-scrolling.  Have the small pics become the big pics on consecutive "scrolls".  So they start w/ a small, become bigger the very next scroll, and finally one more as the biggest photo, then they are gone.  This is great for the "hey check out that pic!" person.

3.  Any way to control an active screensaver?  pause, fwd, back?

4. Start up times are about 1 min to go to screensaver or to the first photo album after you click the button.  Well worth the wait, but if this could be reduced, all the better.

**Comment by timrit** [comment] 2018-02-01 18:55
Day 3 update:  Probably just a quirk in my Internet or Roku, but the screensaver started scrolling w/ just the splash screens as images (the PhotoView splash screen) tried it twice w/ same results.  Then opened app and it seemed to work normally, went back to home screen and the screensaver seemed to be working normally as well...only time I've noticed it and it's come on dozens of times in the past 3 days.

One other minor issue, every few seconds (3-4 sec), it does a slight pause or stutter.  So instead of the smooth scroll, all pics stop for about a split second (1/10th of sec?).

**Comment by chtaylo2** [comment] 2018-02-02 06:19
@timrit - 1. This will not make v2.0, but will investigate for a future release.
2. Can look into this. This is modeled after the Apple TV scrolling photos.  
3. No, screensaver from Roku does not support any buttons. But, everything you can do/see in the screensaver can be done in the channel with full control.
4. I remember you saying how many photos you had. This is likely due to the amount of time the API is taking from Google to return your album listing. Having 110,000, thats alot!

If the PhotoView splash screen images were scrolling this is because the API request timed out or your API token didn't refresh.  I can't duplicate, so not sure.

**Comment by chtaylo2** [comment] 2018-02-21 05:32
Thanks again for testing @timrit 

Roku has approved the release and it went live today. Closing issue

**Closed by chtaylo2** 2018-02-21 05:32 UTC
Labels: bug
