### ISSUE TITLE
Still seeing archived photos

### ISSUE THREAD

**Issue by rewallac** [chtaylo2/Roku-GooglePhotos#162] opened 2019-01-08 15:13 UTC
I am also seeing archived photos in the screensaver. Is there a way to force a refresh after new photos are moved to the archive?

_Originally posted by @rewallac in https://github.com/chtaylo2/Roku-GooglePhotos/issues/60#issuecomment-450516449_

**Comment by chtaylo2** [comment] 2019-01-08 18:43
What albums do you have selected for your screensaver? Are these archived photos tagged to any album?

Archived photos are blacklisted if pulling from the default "Timeline Album". By design, they still show if tagged in a separate album. Seems like that's what's happening here or you just archived and the screensaver hasn't restarted.  The pull happens at the time the screensaver kicks off, it doesn't refresh after fact.

**Comment by rewallac** [comment] 2019-01-10 00:13
I do not have any albums selected. The archived photos are not associated with any albums.

Just so I understand, if I were to see the screensaver, then browse the main roku menu, for a few minutes, when the screensaver kicks back in will that be a full refresh?

Thanks!

**Comment by 6at32off** [comment] 2019-03-05 15:40
I am having a great deal of trouble with Photoview displaying photos from the archive. I have tried everything. These archived photos are not in any album. I have refreshed, restarted, deleted the app and reinstalled and etc.

**Comment by rewallac** [comment] 2019-03-08 19:11
Also still having this issue. @chtaylo2 your previous questions seem to imply there is a way to select an album for the screensaver, but I am not seeing that option.

**Comment by chtaylo2** [comment] 2019-03-14 04:31
This will be fixed with the release of version 3.0. In the new API from Google, we are not even pulling back achieved photos.

**Closed by chtaylo2** 2019-03-14 04:31 UTC
Labels: question

**Comment by rewallac** [comment] 2019-03-14 13:55
@chtaylo2 thanks for the update. Few questions:

Do you have a timeline for 3.0 release?

Your previous questions/responses seem to imply there is a way to select an album for the screensaver, is there a way to do that?
