### ISSUE TITLE
Photoview app on Roku TV keeps crashing

### ISSUE THREAD

**Issue by caltam** [chtaylo2/Roku-GooglePhotos#192] opened 2019-03-27 17:46 UTC
Photoview app crashes and freaks out my TCL Roku TV at the point of entering the registration code.  I had initial success with app last week when I first downloaded but noticed it asked me to re-register when I attempted to use the app for screen saving—at that time it wouldn’t let me re-register. I removed the app and re-downloaded, thinking that might solve the issue but now after downloading and attempting to register using my iPad, the app crashes, freaks out the screen and I can’t navigate out of it. The only solution being to unplug the set in order to reset the TV.

**Comment by chtaylo2** [comment] 2019-03-29 03:46
@caltam -- Could you please take a short video of this happening and email it to me? 
rokuphotoview@gmail.com

I've not heard of this happening before. Do you have issues with any other channels?

**Comment by Rob-in-la** [comment] 2019-03-29 15:41
I have no idea if this is related, but a couple of weeks ago my new Hisense Roku TV started displaying menus on top of each other.  When the screen saver would start, it would flicker like a strobe light.  You couldn't really tell what pictures were up.  When I did a factory reset on the TV, all of this went away.  I'm not sure if this was related to the Photoview app, but I returned the TV just in case it was defective (I was right at the end of the 90-day return window.)  Attached is a picture of the weird menus on top of each other.
![IMG_20190319_201411](https://user-images.githubusercontent.com/46831663/55244423-659f6a00-51fe-11e9-8364-894149707944.jpg)

**Comment by caltam** [comment] 2019-03-29 16:30
Yes, that is very similar to what happens to my screen. It happens as soon
as the TV tries to use the app as a screensaver. If I disable screensaver,
the app functions fine.
—Craig

**Comment by chtaylo2** [comment] 2019-03-29 16:52
I've seen that before as well on a Roku without PhotoView installed, when trying to load a screensaver Just the clock in my case. I think this is bug in the Roku OS vs this channel.  I've seen it randomly.

**Comment by Rob-in-la** [comment] 2019-04-01 03:41
OK, now I have seen the exact same issue on a Roku Ultra connected to another one of my TVs.  My registration was no longer connected, so I tried to reregister.  After registering, it screwed up all my menus just like the picture above.  I managed to uninstall the Photoview app and my Roku box started working again.  I'm surprised that an app can have this level of control over the Roku system.  Hopefully, Chris can figure this out and make the app awesome again!  I suspect this is all related to Google and their changes with accessing the photos.

**Comment by caltam** [comment] 2019-04-01 15:32
I've already tried uninstalling/reinstalling the app but same result so
far.  I don't think doing a TV reset will solve the problem as is does
appear to be screensaver vs app related. Chris-- let me know if you have
any suggestions.

--Craig

**Comment by chtaylo2** [comment] 2019-04-01 23:12
@caltam -- In your video, you were on the registration screen, your screensaver triggered and the screen distorted. Had you actually registered the device to your account?

**Comment by caltam** [comment] 2019-04-01 23:29
I believe on that test--I had time to enter the code on my iPad before the
screensaver kicked in.  When I initially discovered the issue, I had
registered successfully, was viewing photos with no problems--it was only
later when I tried to connect the app as my screensaver that I first
encountered the problem.

-Craig

**Comment by chtaylo2** [comment] 2019-04-02 04:20
The original issue reported by @caltam has been fixed in this bug report #199. This will only fix the issue where a screensaver starts up w/o an active registration. 

With an active registration, I've not been able to duplicate. @caltam / Anyone - If you see this again, please send over a short video demonstrating: rokuphotoview@gmail.com

**Comment by caltam** [comment] 2019-04-03 02:20
Issue resolved itself today — I did change the TV from a wireless internet
connection to wired before attempting to use the app as my screensaver but
have no idea if that was the difference and I’m afraid to revert and have
the problem again. Anyway, thanks for helping.
—Craig

**Comment by Rob-in-la** [comment] 2019-04-16 02:49
I just bought a TCL Roku TV to replace my HiSense that I returned and I'm having the exact same issue with the jumbled menus.  Here is what I did.  I installed the app and connected it to my Google account yesterday.  Everything seemed to be working fine (except not in random order.)  

Today it wasn't pulling up any photos and said that no album was selected.  I tried to select an album but it would not bring up my albums.  So I tried reconnecting it to my Google account.  I got the same jumbled menus that I got with the HiSense Roku TV.  Here are my settings:

- 4K photos
- Delay set to 990 seconds
- Screensaver starts after 1 minute
- Random order
- One album selected that has about 25 photos in it

I did manage to select a different screen saver and start it (which is very difficult when you can't actually read the menus!).  That restored the menus back to normal.  I uninstalled the app, reinstalled it, and reconnected it to my Google account.  It jumbled the menus immediately.  There must be some data stored on the TV since it went back to the original state even after an app reinstall.

**Comment by caltam** [comment] 2019-04-17 23:24
Is your TV wired or wirelessly connected to your internet router---it may
have been coincidental but I connected it directly to my router (rather
than going wireless) and the next time I turned on the set --it worked.

--Craig

**Comment by Rob-in-la** [comment] 2019-04-18 20:40
It's wireless.  I don't have a router nearby so it would be difficult to
connect directly.

**Comment by DuncanMack** [comment] 2019-05-14 12:11
I've had the same experience multiple times. I will try and re-create it, or at least capture it when it happens.

**Comment by chtaylo2** [comment] 2020-05-26 03:48
Unable to reproduce issue on Roku TV. Anyone still seeing this issue?

**Closed** 2020-07-06 02:11 UTC
