### ISSUE TITLE
Amazon Prime Video crashes entire box when calling screen saver

### ISSUE THREAD

**Issue by Eserim** [chtaylo2/Roku-GooglePhotos#123] opened 2018-06-09 21:22 UTC
Ok - I don't know which app is to blame here, but when the Roku box is using the Amazon Prime Video app and calls this screensaver it is crashing the entire box.

The Roku screen savers don't have the issue and it is only recently this has started happening.

Cheers

Eserim

**Comment by chtaylo2** [comment] 2018-07-09 03:50
I tested this and confirmed the Amazon Prime Video app has it's own built in screensaver. So when your "wait time" hits when the Prime Video is open, it won't actually show the PhotoView App.  For me, the screen just went black.  Is that what you are seeing?

If you select another screensaver, and open amazon prime video, does it do the same thing?

**Comment by Eserim** [comment] 2018-07-09 18:11
Alas, that's different to my box.

With the default Roku clock screensaver  Amazon Prime uses that and it does so fine.

With yours it crashes the entire box, it restarts it.

I cannot see any setting in the Amazon Prime  app for screensaver - in fact there aren't really any settings there at all!  I can't even tell you the version of the app!

**Comment by brandilton** [comment] 2018-07-13 21:02
I'm having the same issue with the slacker app.  i don't see any settings in Slacker to adjust screensaver settings.  If i put on clock, it works fine.  on Google Photos, reboots the entire box (a couple times in a row, then goes back to default).  Google Photos screensaver works fine from home screen, just not Slacker for me.

**Comment by brandilton** [comment] 2018-07-13 21:19
a little more testing...  the built in clock and city stroll screensavers work fine with slacker.  Photo collage (is this one built in??) and photoview crash slacker when it kicks on

**Comment by Eserim** [comment] 2018-07-14 20:29
Found version number  for Amazon Prime App  - 10.1 20018070916

**Comment by chtaylo2** [comment] 2021-02-05 05:19
Have not been able to duplicate this issue. Closing since it's been 2.5 years.

**Closed by chtaylo2** 2021-02-05 05:19 UTC
Labels: question
