### ISSUE TITLE
OAuth2 polling request failed

### ISSUE THREAD

**Issue by fmalekzadeh** [chtaylo2/Roku-GooglePhotos#28] opened 2017-01-23 02:15 UTC
Hello. Having an error which i think is linked to one particular Gmail account. 

I'm trying to link my, my mom's and my dad's Google accounts so that we can all view each other's photo albums. If i add mine (or my dad's) first,  no problem. As soon as i add my mom (or try her Gmail account first), i get an OAuth error. 

     OAuth2 polling request failed
     Missing user data
     Try again | Back

If i hit "try gain," i go through the same loop and error. If i hit back,  i get the congratulations bug (someone else submitted this), and i can get in and see the account. It works too.

But then,  if i exit the app and go back in, it craps out and wants me to relink.

Using v3 of the photos app on a Roku Express (which i bought solely for this purpose).

Any help would be appreciated!

**Comment by fmalekzadeh** [comment] 2017-01-23 02:40
Also noticed that for my mom's account, her friendly name (the name which should appear above her email address on the 'select user') is blank. So there may be something missing.

**Comment by chtaylo2** [comment] 2017-01-23 04:26
Thanks fmalekzadeh for the report. I have a potential fix for the issue which I'd like to have you test, since I can't duplicate here. It'll have you install a private channel ID. Please give me your email address, and I'll send you the code.

Thanks
/Chris

**Comment by fmalekzadeh** [comment] 2017-01-23 09:33
Wow. That was fast!

fmalekzadeh@gmail.com

Thanks, Chris!

Doon

---
Sent from my prominently branded mobile device. Please accuse Annie Ms.
Steaks.

**Comment by chtaylo2** [comment] 2017-01-24 04:35
Confirmed issue was related to a third party email. Google API does not provide a name when this type of account is used. Fixed in v.3.727.20170123.

Will be published to Roku store in the next couple weeks as part of Release v.1.6

**Closed by chtaylo2** 2017-01-24 04:35 UTC
Labels: bug

**Comment by fmalekzadeh** [comment] 2017-01-24 05:38
The email i was using and having trouble with was a Gmail account, though.

I'm wondering if it has to do with how the email address is formatted:

     12name@gmail.com

Thoughts?
Doon

---
Sent from my prominently branded mobile device. Please accuse Annie Ms.
Steaks.

**Comment by chtaylo2** [comment] 2017-01-24 14:37
Doon, Can you confirm if the test channel I sent yesterday work for you?

**Comment by fmalekzadeh** [comment] 2017-01-25 05:46
Hey Chris.

I'm traveling on business right now, but will try the link once I'm home on
Friday. I will let you know!

Thanks,
doon

*Feridoon Malekzadeh* | *UX Design Manager & Creative Director*

Email: fmalekzadeh@gmail.com

Phone: 206.832.6296



LinkedIn: http://www.linkedin.com/in/fmalekzadeh

URL: http://feridoon.malekzadeh.net
