### ISSUE TITLE
Day in History stuck

### ISSUE THREAD

**Issue by timrit** [chtaylo2/Roku-GooglePhotos#217] opened 2019-04-24 17:34 UTC
Using the "This Day in History" option, screensaver is only showing two pictures, will show one, then it will show the other only, and it will stay on that pic, although it will update and change the year by one year, but it is the same pic and won't ever change. 

I'm using v3.2 updated on 4/22/19 .  When I do a manual search within G Photos I get the following results:  using today, April 24, I have a range of 55 items from 2018 to 1995 with 9 videos and 3 in archive.  Settings are 720p, Fading w/blur, 10 sec, Random, linked to one user.  

Of the two photos that are showing, there doesn't seem to be anything special about them, both jpgs: one is a PhotScan pic, the other is a shot taken w/ my iphone.   The rest of the pics not showing are just a mix of other jpgs.

"This Week in History" seems to be working fine...Haven't checked "this Month".

**Comment by timrit** [comment] 2019-04-25 20:08
UPDATE:  This seems related, so I will include w/ this issue, but "This Week in History" also seems to have issues.  After an indeterminate amount of time (between 15 and 60 minutes but well under 4 hour limit), the screen goes to black, but I can still see the date in the upper left corner updating every 10 seconds (per settings above) as if it is supposed to be showing a new picture...but stays black.

**Comment by chtaylo2** [comment] 2019-06-02 19:40
@timrit - The two photos failing to rotate is a duplicate of this issue ( #191 ). Hope to have it fixed soon.  The "Time in History" currently only pulls 5 previous years of photos for that time range. While not ideal, Google only allows 5 filters per API search.  This should be expanded in the future to include more years.

**Closed by chtaylo2** 2019-06-02 19:40 UTC
