### ISSUE TITLE
hangouts are displaying / not all albums are

### ISSUE THREAD

**Issue by jradar** [chtaylo2/Roku-GooglePhotos#54] opened 2017-05-28 01:26 UTC
how do you stop from displaying hangouts?? that makes this unusable for me b/c i consider those private conversations and don't want to display the pics from them to anybody

also, not all albums are showing up?

other than those 2 nitpicky items, this app is great

**Comment by chtaylo2** [comment] 2017-07-08 00:25
I'll look at hiding the Hangout albums from the list. I'd never used this feature before.

Google's API does not allow showing of Shared Albums which is likely the cause of "some albums not showing"

Thanks for opening a request.

**Comment by chtaylo2** [comment] 2017-11-01 18:20
Closing issue. This has been fixed in Release 1.7 (https://github.com/chtaylo2/Roku-GooglePhotos/releases/tag/1.7)  Update has been pushed to Roku for publishing.

**Closed by chtaylo2** 2017-11-01 18:20 UTC
Labels: enhancement
